# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactiveStudy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactiveStudy
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'

  target 'ReactiveStudyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReactiveStudyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
